### PR TITLE
Added rake task, organized, added test project, etc.

### PR DESCRIPTION
**Pull request by adamstac**
This is a neat project and there are a number of ways to make this better. I'd be happy to give you some guidance on taking this further.

This is a quick update based on me tinkering with it. I ...
- Added a rake task to convert Sass to SCSS
- Organized things a bit
- Added a test project (assumes Compass)
- Updated modular-scale to be a little easier to use with defaults set

The usage of two [Sass number functions](http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html#number_functions) could also be added `floor()` and `ceil()` to round up or down the final value to avoid sub-pixel issues.

### CODE REVIEW

**Comment by adamstac** [comment]
Also, we're just a few steps away from turning this into a Compass extension.

**Comment by scottkellum** [comment]
Looks good! not sure why anyone would use a default setup as every value will probably be different every time for everyone but always a good thing to have :)

**Comment by adamstac** [comment]
Yea, that's actually my bad. Realized that you'd not want to set those to use `!default` but figured you might catch that :)

**Comment by scottkellum** [comment]
They don't hurt to have in the mixin but the test should be tweaked. On the clock with other projects now but definitely stuff to refine later.

**Pull request merged**
