### PR TITLE
Lace multiple ratios

### PR DESCRIPTION
**Pull request by codingdesigner**
One thing I really think is useful about Tim's original concept was how he laced the results of a two ratios in order to come up with a tighter and more useful set of values. I decided that it could be possible to do this by checking to see if the user passed in a list of ratios, or just a single ratio, and then pulling all those results together. The tricky part was sorting the lists together. 

I'm sure this could use copious refactoring. :)

### CODE REVIEW

**Comment by adamstac** [comment]
Fellas I think I'm the only one with access to push to RubyGems for now. If you have an account there, I think it needs to match up with the email listed in the gemspec to give you push access to the gem there. I don't mind doing that for us though, just need to know when to version and release.

Mason, I haven't had a chance to look at your code yet, but let me know what the state is and whether I should prep a new version for us or we need to do more testing.

Notice I added [a tag for v0.0.2](https://github.com/scottkellum/modular-scale/tree/v0.0.2) which also adds a snapshot of that in the downloads. Tagging when releasing is important to give folks a versioned download of the project if they are not going the route of Compass.

**Comment by codingdesigner** [comment]
I think the code is probably solid, but I'd like another pair of eyes on it, and to do some testing this evening before making a ton of noise about it. Probably only dotting i's, but it should be done. Aside from testing I want to update the readme to explain the multi-ratio option.

**Comment by adamstac** [comment]
Good deal, then I'll make time to go over things and look at you're new test cases. Was moving that to use Serve helpful? How about the usage of `.rvmrc` and Bundler?

**Comment by codingdesigner** [comment]
I actually haven't used Serve yet so I didn't use any of the new stuff. I plan to check it out soon.

**Comment by adamstac** [comment]
If you use RVM, then it should ask you to trust the `.rvmrc` file in there and create a new gemset for you named after the project name. They you can `bundle install` and then run `serve` inside the `test/` directory.

See also [github.com/jlong/serve](https://github.com/jlong/serve)

**Comment by scottkellum** [comment]
A lot of logic added here that all looks really well done from my read-through of it. The test and docs need work to catch up.

**Comment by codingdesigner** [comment]
I did some work tonight on the readme, test and the docs. I feel like it's looking pretty solid, but please give it a look yourselves.

**Pull request merged**
